### ISSUE TITLE
As owner I need to quickly find out if all my time tracking is synced correctly

### ISSUE THREAD

**Issue by VictorChenLi** [VictorChenLi/one-tracking#1]
- [x] Able to see all synced records
- [x] Able to see all need to sync records
- [x] Able to see all sync error records
